name: Koyeb keepalive

on:
  schedule:
    # UTC (国内 UTC+8)
    - cron: '1 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
    - name: Running keepalive
      env:
        KOY_EB: a601x10b@nqmo.com-sddddDDDDD333322aaaa
      run: |
        python3 koyeb.py
